"use client";
import {useEffect,useState} from "react";
type D={id:string;vehicleType:string;vehicleNumber:string|null;available:boolean;user:{id:string;name:string;email:string;phone:string|null}};type C={id:string;name:string};
type R={id:string;status:string;type:string;pickupLocation:string;pickupTime:string;booking:{id:string;bookingCode:string;user:{name:string;phone:string|null};club:{name:string}};driver:{id:string;user:{name:string}}|null};
export default function TransportAdmin(){
 const [drivers,setDrivers]=useState<D[]>([]),[rides,setRides]=useState<R[]>([]),[clubs,setClubs]=useState<C[]>([]),[role,setRole]=useState(""),[form,setForm]=useState({name:"",email:"",phone:"",password:"",vehicleType:"CAB",vehicleNumber:""}),[clubIds,setClubIds]=useState<string[]>([]);
 const load=()=>{fetch("/api/drivers").then(r=>r.ok?r.json():[]).then(setDrivers);fetch("/api/transport").then(r=>r.ok?r.json():[]).then(setRides);fetch("/api/admin/clubs").then(r=>r.ok?r.json():[]).then(setClubs)};useEffect(()=>{fetch("/api/auth/me").then(r=>r.ok?r.json():null).then(x=>x?.role&&setRole(x.role));load()},[]);
 async function add(){const r=await fetch("/api/drivers",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,clubIds})});if(!r.ok){alert((await r.json().catch(()=>({}))).error||"Unable to create driver");return}setForm({...form,name:"",email:"",phone:"",password:"",vehicleNumber:""});setClubIds([]);load();}
 async function toggle(d:D){const r=await fetch("/api/drivers/"+d.id,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({vehicleType:d.vehicleType,vehicleNumber:d.vehicleNumber,available:!d.available})});if(!r.ok)alert((await r.json().catch(()=>({}))).error||"Unable to update driver");load();}
 async function assign(ride:R,driverId:string){const r=await fetch("/api/transport",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({bookingId:ride.booking.id,driverId})});if(!r.ok){alert("Use the booking record to assign transport.");return}load();}
 async function status(id:string,status:string){const r=await fetch("/api/transport/"+id,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status}));if(!r.ok)alert((await r.json().catch(()=>({}))).error||"Unable to update ride");load();}
 const next=(s:string)=>({PENDING:"ASSIGNED",ASSIGNED:"DRIVER_CONFIRMED",DRIVER_CONFIRMED:"ON_THE_WAY",ON_THE_WAY:"ARRIVED",ARRIVED:"PICKED_UP",PICKED_UP:"COMPLETED"} as Record<string,string>)[s];
 return <main className="pt-32 pb-20"><div className="container"><span className="eyebrow">Operations</span><h1 className="text-5xl font-black mt-3">Transport.</h1>
 {role==="SUPER_ADMIN"&&<div className="card p-6 mt-10"><h2 className="font-black text-xl">Add driver</h2><div className="grid md:grid-cols-3 gap-3 mt-5">{Object.entries(form).map(([k,v])=><input key={k} className="input" type={k==="password"?"password":k==="email"?"email":"text"} placeholder={k} value={v} onChange={e=>setForm({...form,[k]:e.target.value})}/>)}</div><div className="mt-4"><p className="muted text-sm mb-2">Club assignments</p><select multiple className="input min-h-28" value={clubIds} onChange={e=>setClubIds(Array.from(e.target.selectedOptions).map(o=>o.value))}>{clubs.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><button className="btn-primary mt-4" onClick={add}>Create driver</button></div>}
 <div className="grid md:grid-cols-2 gap-4 mt-6">{drivers.map(d=><div className="card p-6" key={d.id}><div className="flex justify-between"><h2 className="font-black text-xl">{d.user.name}</h2><span>{d.available?"Available":"Busy"}</span></div><p className="muted mt-2">{d.vehicleType} · {d.vehicleNumber||"No vehicle number"}</p><p className="muted text-sm mt-2">{d.user.phone||d.user.email}</p>{role==="SUPER_ADMIN"&&<button className="btn-secondary text-sm mt-5" onClick={()=>toggle(d)}>{d.available?"Mark busy":"Mark available"}</button>}</div>)}</div>
 <div className="card p-6 mt-8"><h2 className="font-black text-xl">Pickup assignments</h2><div className="space-y-3 mt-5">{rides.length===0?<p className="muted">No transport bookings yet.</p>:rides.map(r=><div className="border border-white/10 rounded-2xl p-4" key={r.id}><div className="flex flex-col md:flex-row md:items-center md:justify-between gap-3"><div><p className="font-bold">{r.booking.bookingCode} · {r.booking.club.name}</p><p className="muted text-sm mt-1">{r.booking.user.name} · {r.type} · {r.pickupLocation}</p><p className="muted text-sm">{r.driver?.user.name||"Unassigned"} · {r.status}</p></div><div className="flex gap-2 items-center">{!r.driver&&<select className="input max-w-52" defaultValue="" onChange={e=>{if(e.target.value)assign(r,e.target.value)}}><option value="">Assign driver</option>{drivers.filter(d=>d.available&&d.vehicleType===r.type).map(d=><option key={d.id} value={d.id}>{d.user.name}</option>)}</select>}{next(r.status)&&<button className="btn-secondary text-sm" onClick={()=>status(r.id,next(r.status))}>→ {next(r.status)}</button>}</div></div></div>)}</div></div></div>
 </main>
}