"use client";
import {useEffect,useState} from "react";
type P={id:string;name:string;description:string|null;price:string;pricing:"PER_PERSON"|"FLAT";active:boolean;club:{id:string;name:string};_count:{bookings:number}}; type C={id:string;name:string};
export default function PackagesAdmin(){
 const [rows,setRows]=useState<P[]>([]),[clubs,setClubs]=useState<C[]>([]),[form,setForm]=useState({clubId:"",name:"",description:"",price:"",pricing:"PER_PERSON"});
 const load=()=>fetch("/api/admin/packages").then(r=>r.ok?r.json():[]).then(setRows); useEffect(()=>{load();fetch("/api/admin/clubs").then(r=>r.ok?r.json():[]).then(setClubs)},[]);
 async function add(){if(!form.clubId||!form.name||!form.price)return;await fetch("/api/admin/packages",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});setForm({clubId:"",name:"",description:"",price:""});load();}
 async function toggle(p:P){await fetch("/api/admin/packages/"+p.id,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({...p,clubId:p.club.id,active:!p.active})});load();}
 return <main className="pt-32 pb-20"><div className="container"><span className="eyebrow">Operations</span><h1 className="text-5xl font-black mt-3">Packages & pricing.</h1>
 <div className="card p-6 mt-10"><div className="grid md:grid-cols-4 gap-3"><select className="input" value={form.clubId} onChange={e=>setForm({...form,clubId:e.target.value})}><option value="">Select club</option>{clubs.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input className="input" placeholder="Package name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input className="input" placeholder="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><input className="input" placeholder="Price" type="number" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/><select className="input" value={form.pricing} onChange={e=>setForm({...form,pricing:e.target.value})}><option value="PER_PERSON">Per person</option><option value="FLAT">Flat package</option></select></div><button className="btn-primary mt-4" onClick={add}>Add package</button></div>
 <div className="grid md:grid-cols-3 gap-4 mt-6">{rows.map(p=><div className="card p-6" key={p.id}><h2 className="font-black text-xl">{p.name}</h2><p className="muted mt-2">{p.club.name}</p><p className="text-2xl font-black mt-4">₹{p.price}</p><p className="muted text-sm mt-2">{p._count.bookings} bookings · {p.pricing==="FLAT"?"Flat":"Per person"}</p><button className="btn-secondary text-sm mt-5" onClick={()=>toggle(p)}>{p.active?"Deactivate":"Activate"}</button></div>)}</div>
 </div></main>
}