"use client";
import {useEffect,useState} from "react";
type E={id:string;name:string;date:string;startTime:string;capacity:number|null;active:boolean;club:{name:string};_count:{bookings:number}}; type C={id:string;name:string};
export default function EventsAdmin(){
 const [rows,setRows]=useState<E[]>([]),[clubs,setClubs]=useState<C[]>([]),[form,setForm]=useState({clubId:"",name:"",slug:"",date:"",startTime:"",endTime:"",capacity:""});
 const load=()=>fetch("/api/admin/events").then(r=>r.ok?r.json():[]).then(setRows); useEffect(()=>{load();fetch("/api/admin/clubs").then(r=>r.ok?r.json():[]).then(setClubs)},[]);
 async function add(){if(!form.clubId||!form.name||!form.slug||!form.date||!form.startTime)return;await fetch("/api/admin/events",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});setForm({...form,name:"",slug:""});load();}
 return <main className="pt-32 pb-20"><div className="container"><span className="eyebrow">Operations</span><h1 className="text-5xl font-black mt-3">Events.</h1>
 <div className="card p-6 mt-10"><div className="grid md:grid-cols-4 gap-3"><select className="input" value={form.clubId} onChange={e=>setForm({...form,clubId:e.target.value})}><option value="">Select club</option>{clubs.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input className="input" placeholder="Event name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input className="input" placeholder="Slug" value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})}/><input className="input" type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/><input className="input" type="time" value={form.startTime} onChange={e=>setForm({...form,startTime:e.target.value})}/><input className="input" type="time" value={form.endTime} onChange={e=>setForm({...form,endTime:e.target.value})}/><input className="input" type="number" placeholder="Capacity" value={form.capacity} onChange={e=>setForm({...form,capacity:e.target.value})}/></div><button className="btn-primary mt-4" onClick={add}>Create event</button></div>
 <div className="grid md:grid-cols-2 gap-4 mt-6">{rows.map(e=><div className="card p-6" key={e.id}><h2 className="font-black text-xl">{e.name}</h2><p className="muted mt-2">{e.club.name} · {new Date(e.date).toLocaleDateString()} · {e.startTime}</p><p className="muted text-sm mt-2">{e._count.bookings} bookings{e.capacity? " · capacity "+e.capacity:""}</p></div>)}</div>
 </div></main>
}