"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {ArrowLeft,ArrowRight,Check,Car,Users,Bike} from "lucide-react";
declare global {interface Window{Razorpay?:any}}
const steps=["Club & date","Guests","Package","Transport","Payment"];
export default function Book(){
 const [step,setStep]=useState(0),[clubs,setClubs]=useState<any[]>([]),[packages,setPackages]=useState<any[]>([]),[clubId,setClubId]=useState(""),[packageId,setPackageId]=useState(""),[eventId,setEventId]=useState(""),[date,setDate]=useState(""),[guestCount,setGuestCount]=useState(1),[transportType,setTransportType]=useState("NONE"),[pickupLocation,setPickupLocation]=useState(""),[pickupTime,setPickupTime]=useState(""),[booking,setBooking]=useState<any>(),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{Promise.all([fetch("/api/clubs").then(r=>r.json()),fetch("/api/packages").then(r=>r.json())]).then(([c,p])=>{setClubs(c);setPackages(p);if(c[0]){setClubId(c[0].id);if(c[0].events?.[0]){setEventId(c[0].events[0].id);setDate(new Date(c[0].events[0].date).toISOString().slice(0,10))}}if(p[0])setPackageId(p[0].id)}).catch(()=>setError("Unable to load booking options."))},[]);
 const club=clubs.find(c=>c.id===clubId),events=(club?.events||[]).filter((e:any)=>e.active&&new Date(e.date).getTime()>=new Date(new Date().toDateString()).getTime()),clubPackages=packages.filter(p=>p.clubId===clubId&&p.active),pkg=packages.find(p=>p.id===packageId),selectedEvent=events.find((e:any)=>e.id===eventId),total=pkg?(pkg.pricing==="FLAT"?Number(pkg.price):Number(pkg.price)*guestCount):0,advance=Math.round(total*.15*100)/100;
 async function createBooking(){if(!eventId||!date)return setError("Please select an event.");if(transportType!=="NONE"&&!pickupTime)return setError("Please select a pickup time.");setBusy(true);setError("");try{const r=await fetch("/api/bookings",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({clubId,eventId,packageId,guestCount,bookingType:guestCount===1?"SINGLE":guestCount===2?"COUPLE":"GROUP",transportType,pickupLocation:transportType==="NONE"?undefined:pickupLocation,pickupTime:transportType==="NONE"?undefined:new Date(`${date}T${pickupTime}`).toISOString()})});const d=await r.json();if(!r.ok)throw new Error(d.error);setBooking(d);setStep(4)}catch(e){setError(e instanceof Error?e.message:"Unable to create booking")}finally{setBusy(false)}}
 async function pay(){if(!booking)return;setBusy(true);setError("");try{const r=await fetch("/api/payments/order",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({bookingId:booking.id})});const o=await r.json();if(!r.ok)throw new Error(o.error);if(!window.Razorpay)throw new Error("Payment checkout is not loaded. Refresh the page.");new window.Razorpay({key:o.keyId,amount:o.amount*100,currency:o.currency,name:"Live in the City",description:"Club booking advance",order_id:o.orderId,handler:async(v:any)=>{const vr=await fetch("/api/payments/verify",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(v)});const d=await vr.json();if(!vr.ok)throw new Error(d.error);window.location.href="/dashboard/tickets/"+booking.id}}).open()}catch(e){setError(e instanceof Error?e.message:"Payment failed")}finally{setBusy(false)}}
 return <main className="pt-32 pb-20"><script src="https://checkout.razorpay.com/v1/checkout.js" async/><div className="container max-w-4xl"><Link href="/" className="muted text-sm flex items-center gap-2"><ArrowLeft size={15}/> Back home</Link><div className="mt-8"><span className="eyebrow">Reservation</span><h1 className="text-4xl md:text-6xl font-black mt-3">Build your night.</h1><div className="flex gap-2 mt-8">{steps.map((s,i)=><div key={s} className={"h-1 flex-1 rounded "+(i<=step?"bg-lime-300":"bg-zinc-800")}/>)}</div><div className="card mt-8 p-6 md:p-10">{error&&<div className="mb-5 text-red-300 text-sm">{error}</div>}
 {step===0&&<><h2 className="text-2xl font-black">Where are you going?</h2><div className="grid md:grid-cols-2 gap-4 mt-7"><label>Club<select value={clubId} onChange={e=>setClubId(e.target.value)} className="mt-2 w-full bg-zinc-900 border border-zinc-700 rounded-xl p-4">{clubs.map(c=><option key={c.id} value={c.id}>{c.name} — {c.city}</option>)}</select></label><label>Event<select value={eventId} onChange={e=>{const id=e.target.value;setEventId(id);const ev=events.find((x:any)=>x.id===id);if(ev)setDate(new Date(ev.date).toISOString().slice(0,10))}} className="mt-2 w-full bg-zinc-900 border border-zinc-700 rounded-xl p-4"><option value="">Select event</option>{events.map((e:any)=><option key={e.id} value={e.id}>{e.name} · {new Date(e.date).toLocaleDateString()} · {e.startTime}</option>)}</select></label></div>{selectedEvent&&<div className="mt-5 rounded-2xl border border-white/10 p-4 text-sm"><span className="muted">Selected date & time</span><div className="font-bold mt-1">{new Date(selectedEvent.date).toLocaleDateString()} · {selectedEvent.startTime}{selectedEvent.endTime?`–${selectedEvent.endTime}`:""}</div></div>}</>}
 {step===1&&<><h2 className="text-2xl font-black">How many people?</h2><div className="grid grid-cols-3 gap-3 mt-7">{[1,2,4,6,8].map(n=><button key={n} onClick={()=>setGuestCount(n)} className={"card p-5 text-left "+(guestCount===n?"border-lime-300":"")}><Users size={20}/><b className="block mt-4">{n} Guest(s)</b></button>)}</div></>}
 {step===2&&<><h2 className="text-2xl font-black">Choose your package.</h2><div className="grid gap-3 mt-7">{clubPackages.map(p=><button key={p.id} onClick={()=>{setPackageId(p.id);setTransportType(p.kind==="ENTRY_CAB"||p.kind==="FULL_COMBO"?"CAB":p.kind==="ENTRY_BIKE"?"BIKE":"NONE")}} className={"card p-5 flex justify-between text-left "+(packageId===p.id?"border-lime-300":"")}><span><b>{p.name}</b><span className="block muted text-sm mt-1">{p.description||"Premium nightlife access"}</span></span><b>₹{Number(p.price).toLocaleString("en-IN")}{p.pricing==="PER_PERSON"?" / guest":""}</b></button>)}</div></>}
 {step===3&&<><h2 className="text-2xl font-black">Add transport.</h2><div className="grid md:grid-cols-3 gap-3 mt-7">{[["NONE","No pickup",Check],["CAB","Cab pickup",Car],["BIKE","Bike pickup",Bike]].filter(([x])=>{const k=pkg?.kind||"ENTRY_ONLY";return k==="ENTRY_CAB"?x==="CAB":k==="ENTRY_BIKE"?x==="BIKE"&&guestCount===1:k==="FULL_COMBO"?x==="CAB"||(x==="BIKE"&&guestCount===1):x==="NONE"}).map(([x,y,I])=>{const Icon=I as any;return <button key={x as string} onClick={()=>setTransportType(x as string)} className={"card p-6 text-left "+(transportType===x?"border-lime-300":"")}><Icon size={20}/><b className="block mt-5">{y as string}</b></button>})}</div>{transportType!=="NONE"&&<div className="grid md:grid-cols-2 gap-4 mt-6"><label>Pickup location<input value={pickupLocation} onChange={e=>setPickupLocation(e.target.value)} placeholder="Enter pickup location" className="mt-2 w-full bg-zinc-900 border border-zinc-700 rounded-xl p-4"/></label><label>Pickup time<input type="time" value={pickupTime} onChange={e=>setPickupTime(e.target.value)} className="mt-2 w-full bg-zinc-900 border border-zinc-700 rounded-xl p-4"/></label></div>}</>}
 {step===4&&<><h2 className="text-2xl font-black">Confirm & pay.</h2><div className="bg-zinc-900 rounded-2xl p-6 mt-6"><div className="flex justify-between"><span className="muted">Booking total</span><b>₹{total.toLocaleString("en-IN")}</b></div><div className="flex justify-between mt-3"><span className="muted">15% advance</span><b className="text-lime-300">₹{advance.toLocaleString("en-IN")}</b></div></div></>}
 <div className="flex justify-between mt-8"><button disabled={step===0||busy} onClick={()=>setStep(step-1)} className="btn-secondary disabled:opacity-30">Back</button>{step<3?<button disabled={!packageId||busy||(step===0&&(!date||!eventId))} onClick={()=>setStep(step+1)} className="btn-primary flex items-center gap-2 disabled:opacity-40">Continue <ArrowRight size={17}/></button>:step===3?<button disabled={busy||!packageId||!eventId||(transportType!=="NONE"&&(!pickupLocation||!pickupTime))} onClick={createBooking} className="btn-primary disabled:opacity-40">{busy?"Creating…":"Review booking"}</button>:<button disabled={busy} onClick={pay} className="btn-primary flex items-center gap-2 disabled:opacity-40"><Check size={17}/> Pay ₹{advance.toLocaleString("en-IN")}</button>}</div>
 </div></div></div></main>
}