import {NextResponse} from "next/server";
import {getCurrentUser,isSameOrigin} from "@/lib/auth";
import {prisma} from "@/lib/prisma";
import {z} from "zod";
import {writeAuditLog} from "@/lib/audit";
const schema=z.object({clubId:z.string().min(1).optional(),name:z.string().trim().min(2).max(120).optional(),description:z.string().max(500).optional(),price:z.coerce.number().positive().max(10000000).optional(),pricing:z.enum(["PER_PERSON","FLAT"]).optional(),active:z.boolean().optional()});
async function guard(){const u=await getCurrentUser();return u&&["SUPER_ADMIN","CLUB_OWNER"].includes(u.role)?u:null}
export async function PATCH(req:Request,
if(!isSameOrigin(req))return NextResponse.json({error:"Invalid request origin"},{status:403});{params}:{params:Promise<{id:string}>}){const u=await guard();if(!u)return NextResponse.json({error:"FORBIDDEN"},{status:403});try{const id=(await params).id,body=schema.parse(await req.json()),existing=await prisma.package.findUnique({where:{id},include:{club:{select:{ownerId:true}}}});if(!existing)return NextResponse.json({error:"Package not found"},{status:404});if(u.role==="CLUB_OWNER"&&existing.club.ownerId!==u.id)return NextResponse.json({error:"FORBIDDEN"},{status:403});if(body.clubId&&u.role==="CLUB_OWNER"){const target=await prisma.club.findUnique({where:{id:body.clubId},select:{ownerId:true,active:true}});if(!target||!target.active||target.ownerId!==u.id)return NextResponse.json({error:"Club is not available to this user"},{status:403})}const updated=await prisma.package.update({where:{id},data:body});await writeAuditLog({userId:u.id,action:"PACKAGE_UPDATED",entity:"Package",entityId:id,metadata:{changes:{...body,price:body.price!==undefined?"[redacted-price]":undefined}}});return NextResponse.json(updated)}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Invalid package update"},{status:400})}}
export async function DELETE(req:Request,{params}:{params:Promise<{id:string}>}){const u=await guard();if(!u)return NextResponse.json({error:"FORBIDDEN"},{status:403});const id=(await params).id;const existing=await prisma.package.findUnique({where:{id},include:{club:{select:{ownerId:true}}}});if(!existing)return NextResponse.json({error:"Package not found"},{status:404});if(u.role==="CLUB_OWNER"&&existing.club.ownerId!==u.id)return NextResponse.json({error:"FORBIDDEN"},{status:403});const updated=await prisma.package.update({where:{id},data:{active:false}});await writeAuditLog({userId:u.id,action:"PACKAGE_DEACTIVATED",entity:"Package",entityId:id});return NextResponse.json(updated)}
