"use client";
import {useEffect,useState} from "react";
type B={id:string;bookingCode:string;status:string;paymentStatus:string;guestCount:number;totalAmount:string;advanceAmount:string;remainingAmount:string;transportType:string;pickupLocation:string|null;createdAt:string;user:{name:string;phone:string|null};club:{name:string};package:{name:string};event:{date:string;startTime:string}|null};
const statuses=["PENDING_PAYMENT","CONFIRMED","CANCELLED","COMPLETED","EXPIRED","REFUND_PENDING","REFUNDED"];
export default function AdminBookings(){
 const [rows,setRows]=useState<B[]>([]),[q,setQ]=useState(""),[status,setStatus]=useState("");
 const load=()=>{const p=new URLSearchParams();if(q)p.set("q",q);if(status)p.set("status",status);fetch("/api/bookings?"+p).then(r=>r.ok?r.json():[]).then(setRows)};useEffect(load,[]);
 async function update(id:string,next:string){await fetch("/api/bookings/"+id,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:next})});load();}
 const money=(v:string)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(Number(v));
 return <main className="pt-32 pb-20"><div className="container"><span className="eyebrow">Operations</span><h1 className="text-5xl font-black mt-3">Bookings.</h1>
 <div className="card p-5 mt-10"><div className="flex flex-wrap gap-3"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load()} placeholder="Booking ID, name or phone" className="input flex-1 min-w-64"/><select value={status} onChange={e=>{setStatus(e.target.value);setTimeout(load,0)}} className="input"><option value="">All statuses</option>{statuses.map(s=><option key={s}>{s}</option>)}</select><button className="btn-primary" onClick={load}>Search</button></div></div>
 <div className="space-y-3 mt-6">{rows.length===0?<div className="card p-10 text-center muted">No bookings found.</div>:rows.map(b=><div className="card p-5" key={b.id}><div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4"><div><div className="flex flex-wrap gap-2 items-center"><b>{b.bookingCode}</b><span className="text-xs px-2 py-1 rounded-full border border-white/10">{b.status}</span><span className="text-xs px-2 py-1 rounded-full border border-white/10">{b.paymentStatus}</span></div><p className="mt-2">{b.user.name} · {b.user.phone||"No phone"} · {b.club.name}</p><p className="muted text-sm mt-1">{b.package.name} · {b.guestCount} guests · {b.event?new Date(b.event.date).toLocaleDateString():"No event date"} {b.event?.startTime||""}</p><p className="muted text-sm mt-1">{money(b.totalAmount)} total · {money(b.advanceAmount)} advance · {money(b.remainingAmount)} remaining · {b.transportType}</p>{b.pickupLocation&&<p className="muted text-sm mt-1">Pickup: {b.pickupLocation}</p>}</div><div className="flex flex-wrap gap-2">{b.status==="PENDING_PAYMENT"&&["PAID","PARTIAL"].includes(b.paymentStatus)&&<button className="btn-primary text-sm" onClick={()=>update(b.id,"CONFIRMED")}>Confirm</button>}{b.status==="REFUND_PENDING"&&<button className="btn-primary text-sm" onClick={async()=>{const r=await fetch("/api/admin/payments/refund",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({bookingId:b.id})});if(!r.ok){const d=await r.json().catch(()=>({}));alert(d.error||"Refund failed");return}load();}}>Process Refund</button>}{b.status!=="CANCELLED"&&b.status!=="REFUNDED"&&<button className="btn-secondary text-sm" onClick={()=>update(b.id,"CANCELLED")}>Cancel</button>}{b.status==="CONFIRMED"&&<button className="btn-secondary text-sm" onClick={()=>update(b.id,"COMPLETED")}>Complete</button>}</div></div></div>)}</div>
 </div></main>
}